---
- name: handle services
  ansible.builtin.service:
    name: "{{ ler53_item.name }}"
    state: "{{ ler53_item.state }}"
  loop: "{{ ler53_service_handlers }}"
  loop_control:
    loop_var: ler53_item
